# -Dspring.profiles.active=local
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phm?useSSL=true
    username: ${DB_USERNAME} # 用户名
    password: ${DB_PASSWORD} # 密码
---
pet-hospital:
  images-path: D:\code_space\PetHospitalManager\images\ # 照片存储路径
---
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印sql语句